### ISSUE TITLE
Data Modeling - tracking issue

### ISSUE THREAD

**Issue by verdverm** [hofstadter-io/hof#91]
Implements `hof/dm` command for capturing data models as the core to defining applications and generators around. Includes schema, checkpointing, diff, and history.

- implement datamodeling
    - [x] schema
    - [x] load
    - [x] checkpoint
    - [x] introspection [list,info,diff, log]
    - [x] subsumption and possible version bumping
    - [ ] views
    - [ ] way to separate [db models, views, and types]
- expose datamodel & history 
    - [x] calculate stepwise diffs across history
    - [ ] add to `In` fed to template rendering
    - [ ] make history inclusion config, expose at HofGenFile level
    - [ ] add example to hof/docs
- docs and tests
    - [ ] automate tests based on `./test/datamodel/`, include in CI
    - [ ] add reference docs to hof/docs
    - [ ] show example of alternative DM schema still supported by `hof`
